services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: sentinel-mosquitto
    restart: unless-stopped
    networks: [core]
    ports:
      - "0.0.0.0:8883:8883"
      - "10.73.42.1:1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/certs:/mosquitto/certs
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  influxdb:
    image: influxdb:2.7
    container_name: sentinel-influxdb
    restart: unless-stopped
    networks: [core]
    ports:
      - "127.0.0.1:8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_ADMIN_USER}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_ADMIN_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
    volumes:
      - influxdb2-data:/var/lib/influxdb2
      - influxdb2-config:/etc/influxdb2
    user: "0:0"
    cap_add: [CHOWN, FOWNER, DAC_OVERRIDE]
    security_opt: [no-new-privileges:true]
    read_only: true
    tmpfs: [/tmp, /var/tmp]
  telegraf:
    image: telegraf:1.32
    container_name: sentinel-telegraf
    restart: unless-stopped
    network_mode: host
    entrypoint: ["/usr/bin/telegraf","--config","/etc/telegraf/telegraf.conf"]
    environment:
      INFLUXDB_URL: http://127.0.0.1:8086
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      INFLUXDB_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
      MQTT_USER: ${MOSQUITTO_IA_USER}
      MQTT_PASSWORD: ${MOSQUITTO_IA_PASSWORD}
    volumes:
      - /etc/telegraf-host:/etc/telegraf:ro
      - /opt/sentinel-x/scripts:/opt/scripts:ro
      - /var/lib/ap-stations:/var/lib/ap-stations:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/sbin/iw:/usr/sbin/iw:ro
    user: "0:0"
    security_opt: [no-new-privileges:true]
    cap_drop: [ALL]
    read_only: true
    tmpfs: [/tmp, /var/tmp]
  grafana:
    image: grafana/grafana:11.3.0
    container_name: sentinel-grafana
    restart: unless-stopped
    networks: [core]
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      GF_SERVER_HTTP_ADDR: 0.0.0.0
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      INFLUXDB_URL: http://influxdb:8086
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_ADMIN_TOKEN: ${INFLUXDB_ADMIN_TOKEN}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    user: "0:0"
    cap_add: [CHOWN, FOWNER, DAC_OVERRIDE]
    security_opt: [no-new-privileges:true]
    read_only: true
    tmpfs: [/tmp, /var/tmp]
networks:
  core:
    driver: bridge
volumes:
  influxdb2-data:
  influxdb2-config:
  grafana-data:
