[platformio]
default_envs = esp_a

[env]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200

[env:esp_a]
build_src_filter = +<esp_a/>
build_flags = -I include/esp_a
lib_deps =
  adafruit/DHT sensor library
  adafruit/Adafruit Unified Sensor
  knolleary/PubSubClient

[env:esp_b]
build_src_filter = +<esp_b/>
build_flags = -I include/esp_b
board_build.flash_mode = dio
lib_deps =
  knolleary/PubSubClient
  bblanchon/ArduinoJson@^7
